# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'Install NPM packages'
  inputs:
    command: 'install'
    workingDir: '$(workingDir)'

- task: Npm@1
  displayName: 'Run Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
    workingDir: '$(workingDir)'